language: go
go:
- 1.13

jobs:
  include:
    - stage: style
      script:
        - make style
    - stage: unit tests
      script:
        - make test
        - go tool cover -func=coverage.out

stages:
  - style
  - unit tests
